version: '3.9'
services:
  nodeapp:
    image: node:lts-alpine3.17
    container_name: nodeapp
    build: .
    ports:
      - "5000:3000"
    command: node server.js
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"